// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using mart_management;

#nullable disable

namespace mart_management.Migrations
{
    [DbContext(typeof(MartManagementContext))]
    [Migration("20251102141026_FixSeedRealWorldData")]
    partial class FixSeedRealWorldData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.10");

            modelBuilder.Entity("mart_management.Category", b =>
                {
                    b.Property<int>("CategoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("CategoryID");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryID = 1,
                            CategoryName = "Beverages",
                            Description = "Soft drinks, juices, water, etc."
                        },
                        new
                        {
                            CategoryID = 2,
                            CategoryName = "Produce",
                            Description = "Fresh fruits and vegetables."
                        },
                        new
                        {
                            CategoryID = 3,
                            CategoryName = "Snacks",
                            Description = "Chips, cookies, candy, etc."
                        },
                        new
                        {
                            CategoryID = 4,
                            CategoryName = "Dairy & Eggs",
                            Description = "Milk, cheese, yogurt, eggs."
                        },
                        new
                        {
                            CategoryID = 5,
                            CategoryName = "Bakery",
                            Description = "Fresh bread, pastries."
                        },
                        new
                        {
                            CategoryID = 6,
                            CategoryName = "Meat & Seafood",
                            Description = "Packaged and fresh meats."
                        },
                        new
                        {
                            CategoryID = 7,
                            CategoryName = "Pantry",
                            Description = "Canned goods, pasta, sauces."
                        },
                        new
                        {
                            CategoryID = 8,
                            CategoryName = "Cleaning",
                            Description = "Household cleaning supplies."
                        },
                        new
                        {
                            CategoryID = 9,
                            CategoryName = "Office",
                            Description = "Paper, pens, and other supplies."
                        },
                        new
                        {
                            CategoryID = 10,
                            CategoryName = "Electronics",
                            Description = "Batteries, chargers, small gadgets."
                        });
                });

            modelBuilder.Entity("mart_management.Customer", b =>
                {
                    b.Property<int>("CustomerID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("CustomerID");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            CustomerID = 1,
                            Address = "123 Main St",
                            CustomerName = "Liam Wilson",
                            Email = "liam@mail.com",
                            Phone = "555-0201"
                        },
                        new
                        {
                            CustomerID = 2,
                            Address = "456 Oak Ave",
                            CustomerName = "Olivia Moore",
                            Email = "olivia@mail.com",
                            Phone = "555-0202"
                        },
                        new
                        {
                            CustomerID = 3,
                            Address = "789 Pine Ln",
                            CustomerName = "Noah Taylor",
                            Email = "noah@mail.com",
                            Phone = "555-0203"
                        },
                        new
                        {
                            CustomerID = 4,
                            Address = "101 Maple Dr",
                            CustomerName = "Emma Anderson",
                            Email = "emma@mail.com",
                            Phone = "555-0204"
                        },
                        new
                        {
                            CustomerID = 5,
                            Address = "202 Birch Pl",
                            CustomerName = "James Thomas",
                            Email = "james@mail.com",
                            Phone = "555-0205"
                        },
                        new
                        {
                            CustomerID = 6,
                            Address = "303 Cedar Rd",
                            CustomerName = "Sophia Jackson",
                            Email = "sophia@mail.com",
                            Phone = "555-0206"
                        },
                        new
                        {
                            CustomerID = 7,
                            Address = "404 Elm Ct",
                            CustomerName = "William Brown",
                            Email = "william@mail.com",
                            Phone = "555-0207"
                        },
                        new
                        {
                            CustomerID = 8,
                            Address = "505 Spruce Way",
                            CustomerName = "Ava Harris",
                            Email = "ava@mail.com",
                            Phone = "555-0208"
                        },
                        new
                        {
                            CustomerID = 9,
                            Address = "606 Fir Bvld",
                            CustomerName = "Benjamin Martin",
                            Email = "ben@mail.com",
                            Phone = "555-0209"
                        },
                        new
                        {
                            CustomerID = 10,
                            Address = "707 Willow Pass",
                            CustomerName = "Mia Garcia",
                            Email = "mia@mail.com",
                            Phone = "555-0210"
                        });
                });

            modelBuilder.Entity("mart_management.Employee", b =>
                {
                    b.Property<int>("EmployeeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("EmployeeID");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            EmployeeID = 1,
                            Email = "alice@shop.com",
                            FullName = "Alice Smith",
                            PasswordHash = "password",
                            Phone = "555-0101",
                            Role = "Admin",
                            Username = "admin_alice"
                        },
                        new
                        {
                            EmployeeID = 2,
                            Email = "bob@shop.com",
                            FullName = "Bob Johnson",
                            PasswordHash = "password",
                            Phone = "555-0102",
                            Role = "Cashier",
                            Username = "cashier_bob"
                        },
                        new
                        {
                            EmployeeID = 3,
                            Email = "charlie@shop.com",
                            FullName = "Charlie Brown",
                            PasswordHash = "password",
                            Phone = "555-0103",
                            Role = "Stocker",
                            Username = "stocker_charlie"
                        },
                        new
                        {
                            EmployeeID = 4,
                            Email = "dana@shop.com",
                            FullName = "Dana White",
                            PasswordHash = "password",
                            Phone = "555-0104",
                            Role = "Cashier",
                            Username = "cashier_dana"
                        },
                        new
                        {
                            EmployeeID = 5,
                            Email = "eve@shop.com",
                            FullName = "Eve Davis",
                            PasswordHash = "password",
                            Phone = "555-0105",
                            Role = "Stocker",
                            Username = "stocker_eve"
                        },
                        new
                        {
                            EmployeeID = 6,
                            Email = "frank@shop.com",
                            FullName = "Frank Miller",
                            PasswordHash = "password",
                            Phone = "555-0106",
                            Role = "Admin",
                            Username = "admin_frank"
                        },
                        new
                        {
                            EmployeeID = 7,
                            Email = "grace@shop.com",
                            FullName = "Grace Lee",
                            PasswordHash = "password",
                            Phone = "555-0107",
                            Role = "Cashier",
                            Username = "cashier_grace"
                        },
                        new
                        {
                            EmployeeID = 8,
                            Email = "heidi@shop.com",
                            FullName = "Heidi Chen",
                            PasswordHash = "password",
                            Phone = "555-0108",
                            Role = "Cashier",
                            Username = "cashier_heidi"
                        },
                        new
                        {
                            EmployeeID = 9,
                            Email = "ivan@shop.com",
                            FullName = "Ivan Garcia",
                            PasswordHash = "password",
                            Phone = "555-0109",
                            Role = "Stocker",
                            Username = "stocker_ivan"
                        },
                        new
                        {
                            EmployeeID = 10,
                            Email = "judy@shop.com",
                            FullName = "Judy Kim",
                            PasswordHash = "password",
                            Phone = "555-0110",
                            Role = "Stocker",
                            Username = "stocker_judy"
                        });
                });

            modelBuilder.Entity("mart_management.Inventory", b =>
                {
                    b.Property<int>("ProductID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("QuantityInStock")
                        .HasColumnType("INTEGER");

                    b.HasKey("ProductID");

                    b.ToTable("Inventories");

                    b.HasData(
                        new
                        {
                            ProductID = 1,
                            QuantityInStock = 150
                        },
                        new
                        {
                            ProductID = 2,
                            QuantityInStock = 200
                        },
                        new
                        {
                            ProductID = 3,
                            QuantityInStock = 50
                        },
                        new
                        {
                            ProductID = 4,
                            QuantityInStock = 80
                        },
                        new
                        {
                            ProductID = 5,
                            QuantityInStock = 60
                        },
                        new
                        {
                            ProductID = 6,
                            QuantityInStock = 30
                        },
                        new
                        {
                            ProductID = 7,
                            QuantityInStock = 25
                        },
                        new
                        {
                            ProductID = 8,
                            QuantityInStock = 50
                        },
                        new
                        {
                            ProductID = 9,
                            QuantityInStock = 40
                        },
                        new
                        {
                            ProductID = 10,
                            QuantityInStock = 10
                        });
                });

            modelBuilder.Entity("mart_management.Payment", b =>
                {
                    b.Property<int>("PaymentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("AmountPaid")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SaleID")
                        .HasColumnType("INTEGER");

                    b.HasKey("PaymentID");

                    b.HasIndex("SaleID");

                    b.ToTable("Payments");

                    b.HasData(
                        new
                        {
                            PaymentID = 1,
                            AmountPaid = 3.0,
                            PaymentDate = new DateTime(2025, 10, 20, 9, 15, 5, 0, DateTimeKind.Unspecified),
                            PaymentMethod = "Cash",
                            SaleID = 1
                        },
                        new
                        {
                            PaymentID = 2,
                            AmountPaid = 5.9800000000000004,
                            PaymentDate = new DateTime(2025, 10, 20, 10, 30, 10, 0, DateTimeKind.Unspecified),
                            PaymentMethod = "Card",
                            SaleID = 2
                        },
                        new
                        {
                            PaymentID = 3,
                            AmountPaid = 10.5,
                            PaymentDate = new DateTime(2025, 10, 21, 11, 0, 15, 0, DateTimeKind.Unspecified),
                            PaymentMethod = "Card",
                            SaleID = 3
                        },
                        new
                        {
                            PaymentID = 4,
                            AmountPaid = 5.0,
                            PaymentDate = new DateTime(2025, 10, 21, 12, 10, 5, 0, DateTimeKind.Unspecified),
                            PaymentMethod = "Cash",
                            SaleID = 4
                        },
                        new
                        {
                            PaymentID = 5,
                            AmountPaid = 6.0,
                            PaymentDate = new DateTime(2025, 10, 22, 14, 5, 10, 0, DateTimeKind.Unspecified),
                            PaymentMethod = "Cash",
                            SaleID = 5
                        },
                        new
                        {
                            PaymentID = 6,
                            AmountPaid = 5.0,
                            PaymentDate = new DateTime(2025, 10, 22, 15, 20, 30, 0, DateTimeKind.Unspecified),
                            PaymentMethod = "Transfer",
                            SaleID = 6
                        },
                        new
                        {
                            PaymentID = 7,
                            AmountPaid = 4.75,
                            PaymentDate = new DateTime(2025, 10, 23, 16, 0, 20, 0, DateTimeKind.Unspecified),
                            PaymentMethod = "Card",
                            SaleID = 7
                        },
                        new
                        {
                            PaymentID = 8,
                            AmountPaid = 6.0,
                            PaymentDate = new DateTime(2025, 10, 24, 9, 45, 10, 0, DateTimeKind.Unspecified),
                            PaymentMethod = "Other",
                            SaleID = 8
                        },
                        new
                        {
                            PaymentID = 9,
                            AmountPaid = 2.9900000000000002,
                            PaymentDate = new DateTime(2025, 10, 24, 10, 10, 5, 0, DateTimeKind.Unspecified),
                            PaymentMethod = "Cash",
                            SaleID = 9
                        },
                        new
                        {
                            PaymentID = 10,
                            AmountPaid = 4.4000000000000004,
                            PaymentDate = new DateTime(2025, 10, 25, 11, 30, 15, 0, DateTimeKind.Unspecified),
                            PaymentMethod = "Card",
                            SaleID = 10
                        });
                });

            modelBuilder.Entity("mart_management.Product", b =>
                {
                    b.Property<int>("ProductID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CategoryID")
                        .HasColumnType("INTEGER");

                    b.Property<double>("CostPrice")
                        .HasColumnType("REAL");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ReorderLevel")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("UnitPrice")
                        .HasColumnType("REAL");

                    b.HasKey("ProductID");

                    b.HasIndex("CategoryID");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductID = 1,
                            CategoryID = 1,
                            CostPrice = 0.75,
                            ProductName = "Cola Can",
                            ReorderLevel = 50,
                            Status = "Active",
                            Unit = "330ml Can",
                            UnitPrice = 1.5
                        },
                        new
                        {
                            ProductID = 2,
                            CategoryID = 1,
                            CostPrice = 0.40000000000000002,
                            ProductName = "Spring Water",
                            ReorderLevel = 50,
                            Status = "Active",
                            Unit = "500ml Bottle",
                            UnitPrice = 1.0
                        },
                        new
                        {
                            ProductID = 3,
                            CategoryID = 2,
                            CostPrice = 1.5,
                            ProductName = "Apples (Red)",
                            ReorderLevel = 20,
                            Status = "Active",
                            Unit = "kg",
                            UnitPrice = 2.9900000000000002
                        },
                        new
                        {
                            ProductID = 4,
                            CategoryID = 3,
                            CostPrice = 1.75,
                            ProductName = "Potato Chips",
                            ReorderLevel = 30,
                            Status = "Active",
                            Unit = "150g Bag",
                            UnitPrice = 3.5
                        },
                        new
                        {
                            ProductID = 5,
                            CategoryID = 4,
                            CostPrice = 1.2,
                            ProductName = "Milk (Full Cream)",
                            ReorderLevel = 25,
                            Status = "Active",
                            Unit = "1L Carton",
                            UnitPrice = 2.2000000000000002
                        },
                        new
                        {
                            ProductID = 6,
                            CategoryID = 5,
                            CostPrice = 1.0,
                            ProductName = "Sliced Bread",
                            ReorderLevel = 15,
                            Status = "Active",
                            Unit = "Loaf",
                            UnitPrice = 2.5
                        },
                        new
                        {
                            ProductID = 7,
                            CategoryID = 6,
                            CostPrice = 5.0,
                            ProductName = "Ground Beef",
                            ReorderLevel = 10,
                            Status = "Active",
                            Unit = "500g Pack",
                            UnitPrice = 8.9900000000000002
                        },
                        new
                        {
                            ProductID = 8,
                            CategoryID = 8,
                            CostPrice = 2.5,
                            ProductName = "All-Purpose Cleaner",
                            ReorderLevel = 20,
                            Status = "Active",
                            Unit = "750ml Bottle",
                            UnitPrice = 4.75
                        },
                        new
                        {
                            ProductID = 9,
                            CategoryID = 9,
                            CostPrice = 3.0,
                            ProductName = "A4 Paper Ream",
                            ReorderLevel = 10,
                            Status = "Active",
                            Unit = "500 Sheets",
                            UnitPrice = 5.0
                        },
                        new
                        {
                            ProductID = 10,
                            CategoryID = 10,
                            CostPrice = 2.7999999999999998,
                            ProductName = "AA Batteries",
                            ReorderLevel = 15,
                            Status = "Inactive",
                            Unit = "4-Pack",
                            UnitPrice = 6.0
                        });
                });

            modelBuilder.Entity("mart_management.Purchase", b =>
                {
                    b.Property<int>("PurchaseID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("PurchaseDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("SupplierID")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("TotalAmount")
                        .HasColumnType("REAL");

                    b.HasKey("PurchaseID");

                    b.HasIndex("SupplierID");

                    b.ToTable("Purchases");

                    b.HasData(
                        new
                        {
                            PurchaseID = 1,
                            PurchaseDate = new DateTime(2025, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SupplierID = 1,
                            TotalAmount = 112.5
                        },
                        new
                        {
                            PurchaseID = 2,
                            PurchaseDate = new DateTime(2025, 10, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SupplierID = 3,
                            TotalAmount = 75.0
                        },
                        new
                        {
                            PurchaseID = 3,
                            PurchaseDate = new DateTime(2025, 10, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SupplierID = 4,
                            TotalAmount = 140.0
                        },
                        new
                        {
                            PurchaseID = 4,
                            PurchaseDate = new DateTime(2025, 10, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SupplierID = 7,
                            TotalAmount = 72.0
                        },
                        new
                        {
                            PurchaseID = 5,
                            PurchaseDate = new DateTime(2025, 10, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SupplierID = 6,
                            TotalAmount = 30.0
                        },
                        new
                        {
                            PurchaseID = 6,
                            PurchaseDate = new DateTime(2025, 10, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SupplierID = 10,
                            TotalAmount = 125.0
                        },
                        new
                        {
                            PurchaseID = 7,
                            PurchaseDate = new DateTime(2025, 10, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SupplierID = 8,
                            TotalAmount = 125.0
                        },
                        new
                        {
                            PurchaseID = 8,
                            PurchaseDate = new DateTime(2025, 10, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SupplierID = 5,
                            TotalAmount = 120.0
                        },
                        new
                        {
                            PurchaseID = 9,
                            PurchaseDate = new DateTime(2025, 10, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SupplierID = 9,
                            TotalAmount = 28.0
                        },
                        new
                        {
                            PurchaseID = 10,
                            PurchaseDate = new DateTime(2025, 10, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SupplierID = 2,
                            TotalAmount = 80.0
                        });
                });

            modelBuilder.Entity("mart_management.PurchaseDetail", b =>
                {
                    b.Property<int>("PurchaseDetailID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProductID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PurchaseID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Subtotal")
                        .HasColumnType("REAL");

                    b.Property<double>("UnitCost")
                        .HasColumnType("REAL");

                    b.HasKey("PurchaseDetailID");

                    b.HasIndex("ProductID");

                    b.HasIndex("PurchaseID");

                    b.ToTable("PurchaseDetails");

                    b.HasData(
                        new
                        {
                            PurchaseDetailID = 1,
                            ProductID = 1,
                            PurchaseID = 1,
                            Quantity = 150,
                            Subtotal = 112.5,
                            UnitCost = 0.75
                        },
                        new
                        {
                            PurchaseDetailID = 2,
                            ProductID = 3,
                            PurchaseID = 2,
                            Quantity = 50,
                            Subtotal = 75.0,
                            UnitCost = 1.5
                        },
                        new
                        {
                            PurchaseDetailID = 3,
                            ProductID = 4,
                            PurchaseID = 3,
                            Quantity = 80,
                            Subtotal = 140.0,
                            UnitCost = 1.75
                        },
                        new
                        {
                            PurchaseDetailID = 4,
                            ProductID = 5,
                            PurchaseID = 4,
                            Quantity = 60,
                            Subtotal = 72.0,
                            UnitCost = 1.2
                        },
                        new
                        {
                            PurchaseDetailID = 5,
                            ProductID = 6,
                            PurchaseID = 5,
                            Quantity = 30,
                            Subtotal = 30.0,
                            UnitCost = 1.0
                        },
                        new
                        {
                            PurchaseDetailID = 6,
                            ProductID = 7,
                            PurchaseID = 6,
                            Quantity = 25,
                            Subtotal = 125.0,
                            UnitCost = 5.0
                        },
                        new
                        {
                            PurchaseDetailID = 7,
                            ProductID = 8,
                            PurchaseID = 7,
                            Quantity = 50,
                            Subtotal = 125.0,
                            UnitCost = 2.5
                        },
                        new
                        {
                            PurchaseDetailID = 8,
                            ProductID = 9,
                            PurchaseID = 8,
                            Quantity = 40,
                            Subtotal = 120.0,
                            UnitCost = 3.0
                        },
                        new
                        {
                            PurchaseDetailID = 9,
                            ProductID = 10,
                            PurchaseID = 9,
                            Quantity = 10,
                            Subtotal = 28.0,
                            UnitCost = 2.7999999999999998
                        },
                        new
                        {
                            PurchaseDetailID = 10,
                            ProductID = 2,
                            PurchaseID = 10,
                            Quantity = 200,
                            Subtotal = 80.0,
                            UnitCost = 0.40000000000000002
                        });
                });

            modelBuilder.Entity("mart_management.Sale", b =>
                {
                    b.Property<int>("SaleID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CustomerID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("SaleDate")
                        .HasColumnType("TEXT");

                    b.Property<double?>("TotalAmount")
                        .HasColumnType("REAL");

                    b.HasKey("SaleID");

                    b.HasIndex("CustomerID");

                    b.ToTable("Sales");

                    b.HasData(
                        new
                        {
                            SaleID = 1,
                            CustomerID = 1,
                            PaymentMethod = "Cash",
                            SaleDate = new DateTime(2025, 10, 20, 9, 15, 0, 0, DateTimeKind.Unspecified),
                            TotalAmount = 3.0
                        },
                        new
                        {
                            SaleID = 2,
                            CustomerID = 2,
                            PaymentMethod = "Card",
                            SaleDate = new DateTime(2025, 10, 20, 10, 30, 0, 0, DateTimeKind.Unspecified),
                            TotalAmount = 5.9800000000000004
                        },
                        new
                        {
                            SaleID = 3,
                            CustomerID = 1,
                            PaymentMethod = "Card",
                            SaleDate = new DateTime(2025, 10, 21, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            TotalAmount = 10.5
                        },
                        new
                        {
                            SaleID = 4,
                            CustomerID = 3,
                            PaymentMethod = "Cash",
                            SaleDate = new DateTime(2025, 10, 21, 12, 10, 0, 0, DateTimeKind.Unspecified),
                            TotalAmount = 5.0
                        },
                        new
                        {
                            SaleID = 5,
                            PaymentMethod = "Cash",
                            SaleDate = new DateTime(2025, 10, 22, 14, 5, 0, 0, DateTimeKind.Unspecified),
                            TotalAmount = 6.0
                        },
                        new
                        {
                            SaleID = 6,
                            CustomerID = 5,
                            PaymentMethod = "Transfer",
                            SaleDate = new DateTime(2025, 10, 22, 15, 20, 0, 0, DateTimeKind.Unspecified),
                            TotalAmount = 5.0
                        },
                        new
                        {
                            SaleID = 7,
                            CustomerID = 8,
                            PaymentMethod = "Card",
                            SaleDate = new DateTime(2025, 10, 23, 16, 0, 0, 0, DateTimeKind.Unspecified),
                            TotalAmount = 4.75
                        },
                        new
                        {
                            SaleID = 8,
                            PaymentMethod = "Other",
                            SaleDate = new DateTime(2025, 10, 24, 9, 45, 0, 0, DateTimeKind.Unspecified),
                            TotalAmount = 6.0
                        },
                        new
                        {
                            SaleID = 9,
                            CustomerID = 10,
                            PaymentMethod = "Cash",
                            SaleDate = new DateTime(2025, 10, 24, 10, 10, 0, 0, DateTimeKind.Unspecified),
                            TotalAmount = 2.9900000000000002
                        },
                        new
                        {
                            SaleID = 10,
                            CustomerID = 4,
                            PaymentMethod = "Card",
                            SaleDate = new DateTime(2025, 10, 25, 11, 30, 0, 0, DateTimeKind.Unspecified),
                            TotalAmount = 4.4000000000000004
                        });
                });

            modelBuilder.Entity("mart_management.SaleDetail", b =>
                {
                    b.Property<int>("SaleDetailID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProductID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SaleID")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Subtotal")
                        .HasColumnType("REAL");

                    b.Property<double>("UnitPrice")
                        .HasColumnType("REAL");

                    b.HasKey("SaleDetailID");

                    b.HasIndex("ProductID");

                    b.HasIndex("SaleID");

                    b.ToTable("SaleDetails");

                    b.HasData(
                        new
                        {
                            SaleDetailID = 1,
                            ProductID = 1,
                            Quantity = 2,
                            SaleID = 1,
                            Subtotal = 3.0,
                            UnitPrice = 1.5
                        },
                        new
                        {
                            SaleDetailID = 2,
                            ProductID = 3,
                            Quantity = 2,
                            SaleID = 2,
                            Subtotal = 5.9800000000000004,
                            UnitPrice = 2.9900000000000002
                        },
                        new
                        {
                            SaleDetailID = 3,
                            ProductID = 4,
                            Quantity = 3,
                            SaleID = 3,
                            Subtotal = 10.5,
                            UnitPrice = 3.5
                        },
                        new
                        {
                            SaleDetailID = 4,
                            ProductID = 9,
                            Quantity = 1,
                            SaleID = 4,
                            Subtotal = 5.0,
                            UnitPrice = 5.0
                        },
                        new
                        {
                            SaleDetailID = 5,
                            ProductID = 2,
                            Quantity = 6,
                            SaleID = 5,
                            Subtotal = 6.0,
                            UnitPrice = 1.0
                        },
                        new
                        {
                            SaleDetailID = 6,
                            ProductID = 6,
                            Quantity = 2,
                            SaleID = 6,
                            Subtotal = 5.0,
                            UnitPrice = 2.5
                        },
                        new
                        {
                            SaleDetailID = 7,
                            ProductID = 8,
                            Quantity = 1,
                            SaleID = 7,
                            Subtotal = 4.75,
                            UnitPrice = 4.75
                        },
                        new
                        {
                            SaleDetailID = 8,
                            ProductID = 1,
                            Quantity = 4,
                            SaleID = 8,
                            Subtotal = 6.0,
                            UnitPrice = 1.5
                        },
                        new
                        {
                            SaleDetailID = 9,
                            ProductID = 3,
                            Quantity = 1,
                            SaleID = 9,
                            Subtotal = 2.9900000000000002,
                            UnitPrice = 2.9900000000000002
                        },
                        new
                        {
                            SaleDetailID = 10,
                            ProductID = 5,
                            Quantity = 2,
                            SaleID = 10,
                            Subtotal = 4.4000000000000004,
                            UnitPrice = 2.2000000000000002
                        });
                });

            modelBuilder.Entity("mart_management.Supplier", b =>
                {
                    b.Property<int>("SupplierID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ContactPerson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SupplierName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("SupplierID");

                    b.ToTable("Suppliers");

                    b.HasData(
                        new
                        {
                            SupplierID = 1,
                            Address = "1 Global Way",
                            ContactPerson = "Sarah Chen",
                            Email = "sarah@globalfoods.com",
                            Phone = "555-0301",
                            SupplierName = "Global Foods Inc."
                        },
                        new
                        {
                            SupplierID = 2,
                            Address = "2 Drink Blvd",
                            ContactPerson = "Mike Rivera",
                            Email = "mike@bevco.com",
                            Phone = "555-0302",
                            SupplierName = "Beverage Co."
                        },
                        new
                        {
                            SupplierID = 3,
                            Address = "3 Produce Plaza",
                            ContactPerson = "Tom Green",
                            Email = "tom@freshfarms.com",
                            Phone = "555-0303",
                            SupplierName = "Fresh Farms Ltd."
                        },
                        new
                        {
                            SupplierID = 4,
                            Address = "4 Chip Circle",
                            ContactPerson = "Lisa Ray",
                            Email = "lisa@snackworld.com",
                            Phone = "555-0304",
                            SupplierName = "SnackWorld Distributors"
                        },
                        new
                        {
                            SupplierID = 5,
                            Address = "5 Paper St",
                            ContactPerson = "David Kim",
                            Email = "david@officesupply.com",
                            Phone = "555-0305",
                            SupplierName = "Office Supply Kings"
                        },
                        new
                        {
                            SupplierID = 6,
                            Address = "6 Bread Ln",
                            ContactPerson = "Anna Brody",
                            Email = "anna@hometown.com",
                            Phone = "555-0306",
                            SupplierName = "Hometown Bakery"
                        },
                        new
                        {
                            SupplierID = 7,
                            Address = "7 Milk Row",
                            ContactPerson = "Paul Chu",
                            Email = "paul@dairybest.com",
                            Phone = "555-0307",
                            SupplierName = "Dairy Best"
                        },
                        new
                        {
                            SupplierID = 8,
                            Address = "8 Soap Rd",
                            ContactPerson = "Emily White",
                            Email = "emily@cleansweep.com",
                            Phone = "555-0308",
                            SupplierName = "Clean Sweep Solutions"
                        },
                        new
                        {
                            SupplierID = 9,
                            Address = "9 Circuit Ave",
                            ContactPerson = "Kenji Watanabe",
                            Email = "kenji@techdist.com",
                            Phone = "555-0309",
                            SupplierName = "Tech Distributors"
                        },
                        new
                        {
                            SupplierID = 10,
                            Address = "10 General St",
                            ContactPerson = "Rita Patel",
                            Email = "rita@genco.com",
                            Phone = "555-0310",
                            SupplierName = "General Goods Co."
                        });
                });

            modelBuilder.Entity("mart_management.Inventory", b =>
                {
                    b.HasOne("mart_management.Product", "Product")
                        .WithOne("Inventory")
                        .HasForeignKey("mart_management.Inventory", "ProductID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("mart_management.Payment", b =>
                {
                    b.HasOne("mart_management.Sale", "Sale")
                        .WithMany("Payments")
                        .HasForeignKey("SaleID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sale");
                });

            modelBuilder.Entity("mart_management.Product", b =>
                {
                    b.HasOne("mart_management.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryID");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("mart_management.Purchase", b =>
                {
                    b.HasOne("mart_management.Supplier", "Supplier")
                        .WithMany("Purchases")
                        .HasForeignKey("SupplierID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("mart_management.PurchaseDetail", b =>
                {
                    b.HasOne("mart_management.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("mart_management.Purchase", "Purchase")
                        .WithMany("PurchaseDetails")
                        .HasForeignKey("PurchaseID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("Purchase");
                });

            modelBuilder.Entity("mart_management.Sale", b =>
                {
                    b.HasOne("mart_management.Customer", "Customer")
                        .WithMany("Sales")
                        .HasForeignKey("CustomerID");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("mart_management.SaleDetail", b =>
                {
                    b.HasOne("mart_management.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("mart_management.Sale", "Sale")
                        .WithMany("SaleDetails")
                        .HasForeignKey("SaleID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("Sale");
                });

            modelBuilder.Entity("mart_management.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("mart_management.Customer", b =>
                {
                    b.Navigation("Sales");
                });

            modelBuilder.Entity("mart_management.Product", b =>
                {
                    b.Navigation("Inventory")
                        .IsRequired();
                });

            modelBuilder.Entity("mart_management.Purchase", b =>
                {
                    b.Navigation("PurchaseDetails");
                });

            modelBuilder.Entity("mart_management.Sale", b =>
                {
                    b.Navigation("Payments");

                    b.Navigation("SaleDetails");
                });

            modelBuilder.Entity("mart_management.Supplier", b =>
                {
                    b.Navigation("Purchases");
                });
#pragma warning restore 612, 618
        }
    }
}
